In [17]:
import numpy as np

a = np.random.rand(5) # creates five random gaussian variables stored in array a
print(a)

[0.84207714 0.75090557 0.7628384  0.11706913 0.68356642]


In [18]:
print(a.shape)
# rank 1 array  --> neither a column vector nor a row vector
# dont use rank 1 array if you want to get rid of bugs

(5,)


In [19]:
print(a.T)

[0.84207714 0.75090557 0.7628384  0.11706913 0.68356642]


In [21]:
print(np.dot(a,a.T))

2.335843744090313


In [5]:
# to get rid of this type of bugs use different data structure
a = np.random.rand(5,1)
print(a) # a 5X1 matrix

[[0.15529077]
 [0.26091679]
 [0.0531428 ]
 [0.65208452]
 [0.07909925]]


In [7]:
print(a.T)

[[0.15529077 0.26091679 0.0531428  0.65208452 0.07909925]]


In [8]:
print(a@a.T) # dot product --> np.dot(a,a.T)

[[0.02411522 0.04051797 0.00825259 0.10126271 0.01228338]
 [0.04051797 0.06807757 0.01386585 0.1701398  0.02063832]
 [0.00825259 0.01386585 0.00282416 0.0346536  0.00420356]
 [0.10126271 0.1701398  0.0346536  0.42521423 0.0515794 ]
 [0.01228338 0.02063832 0.00420356 0.0515794  0.00625669]]


In [24]:
b = np.random.rand(5)  # rank 1 array
b = b.reshape((5,1)) # column vector
print(b)

[[0.14115702]
 [0.85727762]
 [0.78882476]
 [0.14260953]
 [0.27142102]]
