In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)   # calculates a'b
toc = time.time()
print("c: " +str(c))
print("Vectorized version: " +str(1000*(toc-tic))+ " ms\n")

c = 0;
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("c: " + str(c))
print("For loop: " + str(1000*(toc-tic)) + " ms")

c: 249757.03911241918
Vectorized version: 201.58934593200684 ms

c: 249757.03911241298
For loop: 1123.061180114746 ms


In [3]:
import numpy as np
v = np.array([1,2,3,4])

u = np.exp(v)
print(u)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [4]:
# log operation
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [5]:
# absolute
np.abs(v)

array([1, 2, 3, 4])

In [6]:
# maximum value between two arrays
np.maximum(v,0)

array([1, 2, 3, 4])

In [7]:
# elementwise square
u = v**2
u

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
# elementwise inverse
1/v

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [19]:
# transposing
a = np.array([u]) # must use third bracket for dimensional change
print(a.T)
b = np.array(u)
print(b.T) # nothing happens

[[ 1]
 [ 4]
 [ 9]
 [16]]
[ 1  4  9 16]
